"""Write the claimed-vs-verified ledger in house format."""


def write_ledger(path, source_report, aitext_findings, claims, model_opinions=None):
    lines = ["# Claimed vs verified ledger", "",
             "_Generated by fabcheck. Signals, not verdicts. A human decides._", ""]

    lines.append("## Flags (human looks first)")
    flags = [f for f in source_report.findings if f.severity == "flag"]
    if flags:
        for f in flags:
            lines.append(f"- **{f.kind}**: {f.detail} | `{f.excerpt}`")
    else:
        lines.append("- none")
    lines.append("")

    lines.append("## Warnings")
    warns = [f for f in source_report.findings if f.severity == "warn"]
    warns += [(k, d, s) for k, d, s in aitext_findings if s == "flag"]
    if warns:
        for f in warns:
            if isinstance(f, tuple):
                lines.append(f"- **{f[0]}**: {f[1]}")
            else:
                lines.append(f"- **{f.kind}**: {f.detail} | `{f.excerpt}`")
    else:
        lines.append("- none")
    lines.append("")

    lines.append("## Claims ranked for review")
    if claims:
        for score, _i, s in claims[:20]:
            lines.append(f"- [{score}] {s}")
    else:
        lines.append("- no claim-shaped sentences found")
    lines.append("")

    if model_opinions:
        lines.append("## Local model opinion (never verification)")
        for sentence, opinion in model_opinions:
            lines.append(f"- {sentence}")
            lines.append(f"  - {opinion.strip()}")
        lines.append("")

    lines.append("## Quarantine guidance")
    lines.append("- Anything under Flags stays out of public surfaces until a")
    lines.append("  human checks the receipt. Same rule we ran on the CCS doc.")
    lines.append("")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return path
